export default [
  // ÜST GİYİM
  {
    id: 'ust-001',
    name: 'Chambray Noktalı Gömlek',
    category: 'ust',
    subcategory: 'gomlek',
    image: '/products/ust/gomlek-zara.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    price: 599,
  },
  {
    id: 'ust-002',
    name: 'Beyaz Basic Tişört',
    category: 'ust',
    subcategory: 'tisort',
    image: '/products/ust/tisort.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    price: 299,
  },
  {
    id: 'ust-003',
    name: 'Oversize Sweatshirt',
    category: 'ust',
    subcategory: 'sweatshirt',
    image: '/products/ust/sweatshirt.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    price: 449,
  },
  {
    id: 'ust-004',
    name: 'Triko Kazak',
    category: 'ust',
    subcategory: 'kazak',
    image: '/products/ust/kazak.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
    price: 699,
  },
  {
    id: 'ust-005',
    name: 'Deri Ceket',
    category: 'ust',
    subcategory: 'ceket',
    image: '/products/ust/ceket.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    price: 1299,
  },
  {
    id: 'ust-006',
    name: 'Slim Fit Blazer',
    category: 'ust',
    subcategory: 'blazer',
    image: '/products/ust/blazer.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
    price: 999,
  },
  // ALT GİYİM
  {
    id: 'alt-001',
    name: 'Slim Fit Pantolon',
    category: 'alt',
    subcategory: 'pantolon',
    image: '/products/alt/pantolon.jpg',
    sizes: ['34', '36', '38', '40', '42'],
    price: 549,
  },
  {
    id: 'alt-002',
    name: 'Midi Etek',
    category: 'alt',
    subcategory: 'etek',
    image: '/products/alt/etek.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    price: 399,
  },
  {
    id: 'alt-003',
    name: 'Bermuda Şort',
    category: 'alt',
    subcategory: 'sort',
    image: '/products/alt/sort.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    price: 329,
  },
  {
    id: 'alt-004',
    name: 'Yüksek Bel Tayt',
    category: 'alt',
    subcategory: 'tayt',
    image: '/products/alt/tayt.jpg',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    price: 249,
  },
  {
    id: 'alt-005',
    name: 'Slim Fit Jean',
    category: 'alt',
    subcategory: 'jean',
    image: '/products/alt/jean.jpg',
    sizes: ['28', '30', '32', '34', '36'],
    price: 649,
  },
]
